Repository it-e-7/hyunique, pull requests merged in 2023-08, with the labels that each got.

#2 [FIX] : 구조 수정
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/resources/mybatis-config.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/datasource-context.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🛠️ FIX

#5 Main Post List and Filter Search
  .gitignore
  hyunique_app/src/main/java/com/kosa5/hyunique/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/FilterController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PageVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostVO.java
  hyunique_app/src/main/resources/img/user_basic_background.jpg
  hyunique_app/src/main/resources/img/user_basic_profile.jpg
  hyunique_app/src/main/resources/mappers/post.xml
  hyunique_app/src/main/resources/mybatis-config.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/datasource-context.xml
  hyunique_app/src/main/webapp/WEB-INF/views/ajax_response.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/infiniteScroll.js
Labels: ✨ FEAT

#9 Seoyoon
  hyunique_app/.idea/.gitignore
  hyunique_app/.idea/compiler.xml
  hyunique_app/.idea/jarRepositories.xml
  hyunique_app/.idea/misc.xml
  hyunique_app/.idea/runConfigurations.xml
  hyunique_app/.idea/vcs.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/posting/controller/PostingController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/posting/mapper/PostingMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/posting/vo/PostingVO.java
  hyunique_app/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/datasource-context.xml
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/WEB-INF/web.xml
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/img/heendy.png
  hyunique_app/src/main/webapp/resources/js/posting.js
  hyunique_app/src/main/webapp/resources/log4j2.xml
  hyunique_app/src/main/webapp/resources/mappers/posting.xml
  hyunique_app/src/main/webapp/resources/mybatis-config.xml
Labels: ✨ FEAT

#4 Kakao&Naver OAuth
  Servers/Tomcat v9.0 Server at localhost-config/catalina.policy
  Servers/Tomcat v9.0 Server at localhost-config/catalina.properties
  Servers/Tomcat v9.0 Server at localhost-config/context.xml
  Servers/Tomcat v9.0 Server at localhost-config/server.xml
  Servers/Tomcat v9.0 Server at localhost-config/tomcat-users.xml
  Servers/Tomcat v9.0 Server at localhost-config/web.xml
  hyunique_app/.idea/runConfigurations.xml
  hyunique_app/pom.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/NaverLoginApi.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/NaverLoginBO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/mapper/UserMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/vo/PostVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/vo/UserVO.java
  hyunique_app/src/main/resources/icon/btnG_comple.png
  hyunique_app/src/main/resources/icon/kakao_login_large_narrow.png
  hyunique_app/src/main/resources/icon/kakao_login_large_wide.png
  hyunique_app/src/main/resources/icon/kakao_login_medium_narrow.png
  hyunique_app/src/main/resources/icon/kakao_login_medium_wide.png
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/datasource-context.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/root-context.xml
  hyunique_app/src/main/webapp/WEB-INF/views/login.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfopage.jsp
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/mybatis-config.xml
Labels: ✨ FEAT

#10 [FEAT] 게시물 상세 페이지, 제품 상세 페이지, 공통 분야 제작
  hyunique_app/pom.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostDetailVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostProductVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostThumbnailVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/controller/ProductController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/mapper/ProductMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/vo/DepartStockVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/vo/ProductDetailVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/vo/StockVO.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/resources/mappers/ProductMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/detail.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/productdetail.css
  hyunique_app/src/main/webapp/resources/img/ic-backward.png
  hyunique_app/src/main/webapp/resources/img/ic-buy.png
  hyunique_app/src/main/webapp/resources/img/ic-like-selected.png
  hyunique_app/src/main/webapp/resources/img/ic-like.png
  hyunique_app/src/main/webapp/resources/img/ic-posttag.png
  hyunique_app/src/main/webapp/resources/img/ic-share.png
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/mybatis-config.xml
Labels: ✨ FEAT, 🎨 STYLE

#13 [Feat] 매퍼 업데이트 및 코드정리
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/FilterController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/FilterPostVO.java
  hyunique_app/src/main/resources/mappers/post.xml
  hyunique_app/src/main/resources/mybatis-config.xml
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
Labels: ✨ FEAT

#12 [FEAT] 제품 별 스타일 페이지, 배포 url 작업
  .gitignore
  hyunique_app/src/main/java/com/kosa5/hyunique/product/controller/ProductController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/mapper/ProductMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductServiceImpl.java
  hyunique_app/src/main/resources/mappers/ProductMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/style.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfopage.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/productstyle.css
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/infiniteScroll.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/posting.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/productstyle.js
Labels: ✨ FEAT, 🪄 REFACTOR

#16 [REFACTOR] : url 배포용으로 전부 수정
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/infiniteScroll.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/posting.js
  hyunique_app/src/main/webapp/resources/js/productstyle.js
Labels: 🪄 REFACTOR
