Repository it-e-7/hyunique, pull requests merged in 2023-09, with the labels that each got.

#20 [FEAT] CSS 및 유저 스타일 로직 수정
  Servers/Tomcat v9.0 Server at localhost-config/server.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/ClosetController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/controller/ClosetController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/mapper/ClosetMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/service/ClosetService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/service/ClosetServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/vo/ClosetVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/NaverLoginBO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/vo/UserVO.java
  hyunique_app/src/main/resources/mappers/Closet.xml
  hyunique_app/src/main/resources/mappers/ProductMapper.xml
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/login.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfopage.jsp
  hyunique_app/src/main/webapp/resources/css/login.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/icon/btnG_comple.png
  hyunique_app/src/main/webapp/resources/icon/facebook_logo.png
  hyunique_app/src/main/webapp/resources/icon/facebook_logo_null.png
  hyunique_app/src/main/webapp/resources/icon/hyuniquelogo.png
  hyunique_app/src/main/webapp/resources/icon/instagram_logo.png
  hyunique_app/src/main/webapp/resources/icon/instagram_logo_null.png
  hyunique_app/src/main/webapp/resources/icon/kakao_login_large_narrow.png
  hyunique_app/src/main/webapp/resources/icon/kakao_login_large_wide.png
  hyunique_app/src/main/webapp/resources/icon/kakao_login_medium_narrow.png
  hyunique_app/src/main/webapp/resources/icon/kakao_login_medium_wide.png
  hyunique_app/src/main/webapp/resources/icon/kakao_login_wide_btn.png
  hyunique_app/src/main/webapp/resources/icon/naver_login_wide_btn.png
  hyunique_app/src/main/webapp/resources/icon/threads_logo.png
  hyunique_app/src/main/webapp/resources/icon/threads_logo_null.png
  hyunique_app/src/main/webapp/resources/icon/twitter_logo.png
  hyunique_app/src/main/webapp/resources/icon/twitter_logo_null.png
  hyunique_app/src/main/webapp/resources/img/ic-accessory.png
  hyunique_app/src/main/webapp/resources/img/ic-bag.png
  hyunique_app/src/main/webapp/resources/img/ic-bottom.png
  hyunique_app/src/main/webapp/resources/img/ic-dress.png
  hyunique_app/src/main/webapp/resources/img/ic-hat.png
  hyunique_app/src/main/webapp/resources/img/ic-outer.png
  hyunique_app/src/main/webapp/resources/img/ic-settings.png
  hyunique_app/src/main/webapp/resources/img/ic-shoes.png
  hyunique_app/src/main/webapp/resources/img/ic-top.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/closet.js
  hyunique_app/src/main/webapp/resources/js/tab.js
Labels: ✨ FEAT

#17 [FEAT] : 모바일 환경 테스트
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/home.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/detail.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/productdetail.css
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
Labels: ✨ FEAT

#22 [Feat] QR코드 리더 기능 추가
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/service/ClosetServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/FilterController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/FilterPostVO.java
  hyunique_app/src/main/resources/log4j2.xml
  hyunique_app/src/main/resources/mappers/post.xml
  hyunique_app/src/main/resources/mybatis-config.xml
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/readQRPage.jsp
  hyunique_app/src/main/webapp/resources/css/QRScanner.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/img/QRTag.png
  hyunique_app/src/main/webapp/resources/img/qr.png
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/jsQR.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/qrCamera.js
Labels: ✨ FEAT

#23 [FEAT] 유저프로필 전체 작업
  hyunique_app/src/main/java/com/kosa5/hyunique/aop/AopAdvice.java
  hyunique_app/src/main/java/com/kosa5/hyunique/interceptor/AuthInterceptor.java
  hyunique_app/src/main/java/com/kosa5/hyunique/interceptor/annotation/Auth.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/resources/log4j2.xml
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/img/ic-allproducts.png
  hyunique_app/src/main/webapp/resources/img/posting-btn.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/closet.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/tab.js
Labels: ✨ FEAT, 🛠️ FIX, 🪄 REFACTOR, 🎨 STYLE

#24 [FEAT] : 검색 기능 및 제품 상세 페이지 미비 기능 구현
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostProductVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/controller/ProductController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/mapper/ProductMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/mapper/UserMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserServiceImpl.java
  hyunique_app/src/main/resources/mappers/ProductMapper.xml
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/style.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/search.jsp
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/productstyle.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/productstyle.js
  hyunique_app/src/main/webapp/resources/js/search.js
Labels: ✨ FEAT, 🎨 STYLE

#25 [DEPLOY] 3차 스프린트 개발 deploy 버전
  hyunique_app/src/main/java/com/kosa5/hyunique/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/closet/service/ClosetServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/api/PostRestController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/FilterController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/PostProductTypeHandler.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Config.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/FilterPostVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PageVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostingVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/api/ProductRestController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/controller/ProductController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/mapper/ProductMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/vo/ProductInformVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/resources/mappers/post.xml
  hyunique_app/src/main/webapp/WEB-INF/views/ajax_response.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/search.jsp
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/closet.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/posting.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/productstyle.js
  hyunique_app/src/main/webapp/resources/js/search.js
Labels: 🛠️ FIX

#26 [DEPLOY] : OAuth redirect uri 배포 환경 분리
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/NaverLoginBO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthService.java
Labels: 🪄 REFACTOR

#28 [FIX] : 하드코딩 수정 및 버그 개선
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/resources/css/productdetail.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/img/ic-close.png
  hyunique_app/src/main/webapp/resources/img/ic-search-n.png
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/search.js
Labels: 🛠️ FIX

#29 [FEAT] 사진 업로드 수정, 유저 정보 업데이트 온보딩, 이미지 리사이징
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserServiceImpl.java
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/login.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/readQRPage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/useronboarding.jsp
  hyunique_app/src/main/webapp/resources/css/login.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/onboarding.css
  hyunique_app/src/main/webapp/resources/img/fashion-person.gif
  hyunique_app/src/main/webapp/resources/img/fashion-person.png
  hyunique_app/src/main/webapp/resources/img/gif-intro.gif
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/onboarding.js
Labels: ✨ FEAT, 🐞 BUG, 🪄 REFACTOR, 🎨 STYLE

#30 [Feat]: QR, Modal Issue resolution, Toss Payments System update
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/controller/PaymentController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/service/TossPayment.java
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/service/TossPaymentService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/vo/TossPaymentVO.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/payment.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/QRScanner.css
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/img/qr.png
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/mypage.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/qrCamera.js
  hyunique_app/src/main/webapp/resources/js/tossPayment.js
Labels: ✨ FEAT, 🐞 BUG, 🛠️ FIX

#33 [Fix] 이미지 처리 로직 변경, 오류 수정 및 CSS
  hyunique_app/pom.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/PostProductTypeHandler.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/vo/PostVO.java
  hyunique_app/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/img/add-img.png
  hyunique_app/src/main/webapp/resources/img/post-main.jpg
  hyunique_app/src/main/webapp/resources/img/pre-main.png
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/pin.js
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
Labels: 🛠️ FIX

#35 [FEAT] : gpt 챗봇
  .gitignore
  Servers/Tomcat v9.0 Server at localhost-config/catalina.policy
  Servers/Tomcat v9.0 Server at localhost-config/catalina.properties
  Servers/Tomcat v9.0 Server at localhost-config/context.xml
  Servers/Tomcat v9.0 Server at localhost-config/server.xml
  Servers/Tomcat v9.0 Server at localhost-config/tomcat-users.xml
  Servers/Tomcat v9.0 Server at localhost-config/web.xml
  hyunique_app/pom.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/controller/GPTController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/service/GPTService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/service/GPTServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/vo/GPTVO.java
  hyunique_app/src/main/java/com/kosa5/hyunique/oauth/OAuthController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/mapper/UserMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/service/UserServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/vo/UserVO.java
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/gptChat.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/login.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/useronboarding.jsp
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/img/ic-bag-check.png
  hyunique_app/src/main/webapp/resources/img/ic-bag-non-check.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/closet.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
Labels: ✨ FEAT, 🛠️ FIX, 🎨 STYLE

#34 [Feat] : GPT검색시, 해당 검색결과에 따른 VO List 리턴
  hyunique_app/pom.xml
  hyunique_app/src/main/java/com/kosa5/hyunique/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/controller/GPTController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/service/GPTService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/service/GPTServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/controller/PaymentController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/payment.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/onboarding.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/tossPayment.js
Labels: ✨ FEAT, 🎨 STYLE

#36 fix : 의존성 수정
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/ListTypeHandler.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/PostProductTypeHandler.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
Labels: 🛠️ FIX

#37 [Fix] css 수정 및 모달 수정
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
Labels: 🛠️ FIX

#39 fix : 유저 프로필, 팔로우 로직 수정
  hyunique_app/src/main/java/com/kosa5/hyunique/gpt/controller/GPTController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
Labels: 🐞 BUG, 🛠️ FIX

#44 Feat: AI챗봇, 결제 흐름완성, 추천순위 등수 이미지 추가
  hyunique_app/src/main/java/com/kosa5/hyunique/payment/controller/PaymentController.java
  hyunique_app/src/main/webapp/WEB-INF/views/gptChat.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/payment.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/paymentSuccess.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/paymentSuccess.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
  hyunique_app/src/main/webapp/resources/js/payment.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/tossPayment.js
Labels: ✨ FEAT, 🛠️ FIX

#47 [FEAT] 이미지 검색 및 css수정
  .gitignore
  ai_server/main.py
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/mapper/PostMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/S3Service.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/controller/ProductController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/mapper/ProductMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/ProductServiceImpl.java
  hyunique_app/src/main/java/com/kosa5/hyunique/product/service/SearchService.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/resources/mappers/ProductMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/imgSearch.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/product/style.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/readQRPage.jsp
  hyunique_app/src/main/webapp/resources/css/QRScanner.css
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/css/productdetail.css
  hyunique_app/src/main/webapp/resources/css/productstyle.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/img/ic-search-camera.png
  hyunique_app/src/main/webapp/resources/img/ic-search-n.png
  hyunique_app/src/main/webapp/resources/js/imgSearch.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/qrCamera.js
  hyunique_app/src/main/webapp/resources/js/search.js
Labels: ✨ FEAT, 🎨 STYLE

#46 [FEAT] gpt,메인,유저,온보딩 css 수정
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/gptChat.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/useronboarding.jsp
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/onboarding.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/icon/logo-hyunique-app.png
  hyunique_app/src/main/webapp/resources/img/banner-text.png
  hyunique_app/src/main/webapp/resources/img/ic-search.png
  hyunique_app/src/main/webapp/resources/img/qr.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/closet.js
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
  hyunique_app/src/main/webapp/resources/js/onboarding.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/tab.js
Labels: 🛠️ FIX, 🎨 STYLE

#49 [FIX] 릴리즈 버그 수정
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/error/404.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/gptChat.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/useronboarding.jsp
  hyunique_app/src/main/webapp/WEB-INF/web.xml
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/onboarding.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/style.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/img/bg.jpg
  hyunique_app/src/main/webapp/resources/img/ic-search-camera.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
  hyunique_app/src/main/webapp/resources/js/onboarding.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/productdetail.js
  hyunique_app/src/main/webapp/resources/js/search.js
Labels: ✨ FEAT, 🐞 BUG, 🛠️ FIX, 🎨 STYLE

#51 [Feat] 이미지 검색 및 버그수정
  hyunique_app/src/main/java/com/kosa5/hyunique/post/util/PostProductTypeHandler.java
  hyunique_app/src/main/resources/mappers/PostMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/imgSearch.jsp
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/img/ic-drag-event.gif
  hyunique_app/src/main/webapp/resources/js/imgSearch/imgSearch.js
  hyunique_app/src/main/webapp/resources/js/imgSearch/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
Labels: ✨ FEAT, 🐞 BUG

#52 [FEAT] : 팔로우 리스트, 좋아요 리스트, 배송지 입력, 배너DB, gpt, 프로필화면, 하단 네비바 수정 및 추가
  hyunique_app/src/main/java/com/kosa5/hyunique/user/controller/UserController.java
  hyunique_app/src/main/resources/mappers/BannerMapper.xml
  hyunique_app/src/main/resources/mappers/UserMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/followList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/footer.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/likeList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/myStylePage.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/userInfoUpdatePage.jsp
  hyunique_app/src/main/webapp/resources/css/QRScanner.css
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/follow.css
  hyunique_app/src/main/webapp/resources/css/footer.css
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/css/login.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/img/ico-nav-ai.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-home.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-my.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-qr.png
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/posting/like.js
  hyunique_app/src/main/webapp/resources/js/qrCamera.js
Labels: ✨ FEAT, 🛠️ FIX, 🎨 STYLE

#54 [FEAT] 유저 링크 추가
  hyunique_app/src/main/webapp/resources/js/follow.js
  hyunique_app/src/main/webapp/resources/js/posting/like.js
Labels: ✨ FEAT, 🛠️ FIX

#55 [Feat] 이미지 검색 페이지 및 CSS 애니메이션
  hyunique_app/src/main/java/com/kosa5/hyunique/post/controller/PostController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/post/service/PostServiceImpl.java
  hyunique_app/src/main/webapp/WEB-INF/views/footer.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/imgSearch.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/post/detail.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/imgSearch/imgSearch.js
  hyunique_app/src/main/webapp/resources/js/imgSearch/modal.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/postdetail.js
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
Labels: ✨ FEAT

#56 [FIX] 유저 배경사진 가운데 위치 수정
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
Labels: 🛠️ FIX

#57 [FIX] 프로필 사진 위치 변경
  hyunique_app/src/main/webapp/resources/css/userStyle.css
Labels: 🛠️ FIX

#60 [Feat] CSS 애니메이션 추가 및 버그 수정
  hyunique_app/src/main/webapp/WEB-INF/views/followList.jsp
  hyunique_app/src/main/webapp/resources/css/follow.css
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/follow.js
  hyunique_app/src/main/webapp/resources/js/imgSearch/imgSearch.js
  hyunique_app/src/main/webapp/resources/js/postList.js
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
Labels: ✨ FEAT, 🐞 BUG

#61 [FEAT] : css 수정 및 팔로우 추천 리스트
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/controller/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/mapper/BannerMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/service/BannerService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/service/BannerServiceImpl.java
  hyunique_app/src/main/resources/mappers/BannerMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/footer.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/postdetail.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/img/hyunique.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-1st.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-2nd.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-3rd.png
  hyunique_app/src/main/webapp/resources/img/ic-person.png
  hyunique_app/src/main/webapp/resources/img/ic-search.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-ai-selected.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-ai.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-home-selected.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-home.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-my-selected.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-my.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-qr-selected.png
  hyunique_app/src/main/webapp/resources/img/ico-nav-qr.png
  hyunique_app/src/main/webapp/resources/js/common.js
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/follow.js
  hyunique_app/src/main/webapp/resources/js/postList.js
Labels: ✨ FEAT, 🛠️ FIX, 🎨 STYLE

#62 [FIX] : 400에러, 유저 프로필 추천 섹션 긴급 수정
  hyunique_app/src/main/webapp/WEB-INF/views/useronboarding.jsp
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/js/UserUpdate.js
Labels: 🐞 BUG, 🛠️ FIX

#63 [Feat] 게시글 작성 튜토리얼
  hyunique_app/src/main/webapp/WEB-INF/views/imgSearch.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/posting.jsp
  hyunique_app/src/main/webapp/resources/css/imgSearch.css
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/js/posting/posting.js
Labels: ✨ FEAT

#64 [Bug] 핀 좌표 수정 및 스크롤 수정
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/posting.css
  hyunique_app/src/main/webapp/resources/js/posting/modal.js
  hyunique_app/src/main/webapp/resources/js/posting/pin.js
Labels: 🐞 BUG

#66 fix: 결제로그 결제선택개수와 결제개수 일치시 문제 해결
  hyunique_app/hyunique.iml
  hyunique_app/src/main/webapp/resources/js/payment.js
Labels: 🛠️ FIX

#67 [FEAT] : gpt,main css
  hyunique_app/src/main/webapp/WEB-INF/views/common.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/followList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/gptChat.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/header.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/likeList.jsp
  hyunique_app/src/main/webapp/WEB-INF/views/postList.jsp
  hyunique_app/src/main/webapp/resources/css/QRScanner.css
  hyunique_app/src/main/webapp/resources/css/filterModal.css
  hyunique_app/src/main/webapp/resources/css/follow.css
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/search.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/css/userupdatestyle.css
  hyunique_app/src/main/webapp/resources/img/ic-ai-chatbot.jpg
  hyunique_app/src/main/webapp/resources/img/ic-back-1st.png
  hyunique_app/src/main/webapp/resources/img/ic-back-2nd.png
  hyunique_app/src/main/webapp/resources/img/ic-back-3rd.png
  hyunique_app/src/main/webapp/resources/img/ic-crown-1st.png
  hyunique_app/src/main/webapp/resources/img/ic-crown-2nd.png
  hyunique_app/src/main/webapp/resources/img/ic-crown-3rd.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-1st.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-2nd.png
  hyunique_app/src/main/webapp/resources/img/ic-medal-3rd.png
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/follow.js
  hyunique_app/src/main/webapp/resources/js/gpt.js
  hyunique_app/src/main/webapp/resources/js/posting/like.js
Labels: ✨ FEAT, 🎨 STYLE

#68 [FEAT] : 스타일랭킹 db 처리, css
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/controller/HomeController.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/mapper/BannerMapper.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/service/BannerService.java
  hyunique_app/src/main/java/com/kosa5/hyunique/banner/service/BannerServiceImpl.java
  hyunique_app/src/main/resources/mappers/BannerMapper.xml
  hyunique_app/src/main/webapp/WEB-INF/views/login.jsp
  hyunique_app/src/main/webapp/resources/css/gpt.css
  hyunique_app/src/main/webapp/resources/css/login.css
  hyunique_app/src/main/webapp/resources/css/main.css
  hyunique_app/src/main/webapp/resources/css/postList.css
  hyunique_app/src/main/webapp/resources/css/productstyle.css
  hyunique_app/src/main/webapp/resources/css/userStyle.css
  hyunique_app/src/main/webapp/resources/js/filterModal.js
  hyunique_app/src/main/webapp/resources/js/postList.js
Labels: ✨ FEAT, 🎨 STYLE
